apps:
    - name: "bot-fb"
      script: ./index.js
      exec_mode: fork
      instances: 1
      merge_logs: true
      error_file: ../logs/error.log
      out_file: ../logs/out.log
      restart_delay: 3000
      max_restarts: 9999999
      env:
        NODE_ENV: development
      env_production:
        NODE_ENV: production
