version: '3.2'
services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "127.0.0.1:${WWW_PORT}:80"
      - "127.0.0.1:${WWW_SSL_PORT}:443"
    volumes:
     - ./web:/var/www/
    depends_on:
      - nodejs
      - db
  nodejs:
    restart: always
    build:
      dockerfile: docker/nodejs/Dockerfile
      context: .
    volumes:
     - ./:/opt/web_secure
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'web_secure'

volumes:
  db_data: